import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class LocalListUpdate extends ChangeNotifier {
  List<Map<String, dynamic>> chatHistory = [
    {
      "id": 1,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Hello Teacher",
      "status": 0,
      "date": "11-Mar-2026",
      "time": "02:08 PM",
    },
    {
      "id": 2,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "How are you ?",
      "status": 0,
      "date": "11-Mar-2026",
      "time": "02:11 PM",
    },
    {
      "id": 3,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Hello",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:18 PM",
    },
    {
      "id": 4,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "I am fine",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:19 PM",
    },
    {
      "id": 5,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "How are you ?",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:21 PM",
    },
    {
      "id": 6,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "I an not well",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:27 PM",
    },
    {
      "id": 7,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "I have fiver",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:28 PM",
    },
    {
      "id": 8,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "And Not Fell well",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:29 PM",
    },
    {
      "id": 9,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Did you see a doctor?",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:31 PM",
    },
    {
      "id": 10,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Yes, the doctor gave me some medicine",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:32 PM",
    },
    {
      "id": 11,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Thats good. You should take rest ",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:33 PM",
    },
    {
      "id": 12,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Yes, teacher. I will",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:34 PM",
    },
    {
      "id": 13,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Dont worry about the missed lesson.",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:35 PM",
    },
    {
      "id": 14,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Thank you",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:36 PM",
    },
    {
      "id": 15,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Take Care",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:37 PM",
    },
    {
      "id": 16,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "Yes Teacher",
      "status": 0,
      "date": "13-Mar-2026",
      "time": "02:39 PM",
    },
    {
      "id": 17,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": "hy",
      "status": 1,
      "date": "11-Mar-2026",
      "time": "02:42 PM",
    },
  ];

  void addNewChat({required String message}) {
    String formattedDate = DateFormat(
      'dd-MMM-yyyy',
    ).format(DateTime.now()); // 11-Mar-2026

    String formattedTime = DateFormat('hh:mm a').format(DateTime.now());

    Map<String, dynamic> newMessage = {
      "id": chatHistory.length + 1,
      "student_name": "Test",
      "scholar_no": "13577",
      "teacher_name": "Abhi Kumawat",
      "designation": "",
      "message": message,
      "status": 0,
      "date": formattedDate.toString(),
      "time": formattedTime.toString(),
    };
    chatHistory.add(newMessage);
    notifyListeners();
    debugPrint("here is message $newMessage");
  }
}
